services:
  db:
    image: mysql:8.0
    container_name: cloudmart-mysql
    environment:
      MYSQL_DATABASE: cloudmart
      MYSQL_USER: cloudmart_user
      MYSQL_PASSWORD: cloudmart_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: cloudmart-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: cloudmart
      DB_USER: cloudmart_user
      DB_PASSWORD: cloudmart_pass
      DB_PORT: "3306"
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:
