apiVersion: v1
kind: Service
metadata:
  name: cloudmart-backend-service
spec:
  selector:
    app: cloudmart-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

